version: 2.1

executors:
  trivy-executor:
    docker:
      - image: aquasec/trivy:latest

jobs:
  trivy-scan:
    executor: trivy-executor
    steps:
      - checkout

      - run:
          name: Run Trivy vulnerability scan (all severities)
          command: |
            trivy fs \
              --ignore-unfixed \
              --format sarif \
              --output trivy-results.sarif \
              --severity LOW,MEDIUM,HIGH,CRITICAL .

      - store_artifacts:
          path: trivy-results.sarif
          destination: trivy-results

workflows:
  version: 2
  security_scan:
    jobs:
      - trivy-scan