version: 2.1

executors:
  trivy-executor:
    docker:
      - image: aquasec/trivy:latest

jobs:
  trivy-scan:
    executor: trivy-executor
    steps:
      - checkout
      - run:
          name: Run Trivy FS Scan
          command: trivy fs --exit-code 0 --severity HIGH,CRITICAL .

workflows:
  version: 2
  scan_only:
    jobs:
      - trivy-scan
